### // // Obtener todos los nombres de Pokemon
GET  http://localhost:3001/pokemon HTTP/1.1


### // Obtener todos los tipos de Pokemon
GET  http://localhost:3001/type HTTP/1.1


### // Buscar Pokemon por ID
GET  http://localhost:3001/pokemon/f187daf3-991d-4f93-b1a4-ef14577d59a5 HTTP/1.1


### // Crear un Pokemon
POST  http://localhost:3001/pokemon HTTP/1.1
Content-Type: application/json

{
    "name": "Prueba",
    "image": "https://acortar.link/2vXTcJ",
    "types": ["Normal", "Fighting"],
    "hp": "1",
    "attack": "1",
    "defense": "1",
    "speed": "1",
    "height": "1",
    "weight": "1"
}

### // Buscar Pokemon por nombre
GET  http://localhost:3001/pokemon?name=Hola HTTP/1.1


### // Actualizar un pokemon
PUT http://localhost:3001/pokemon/ffdae384-8874-476d-92d8-0c160a966a70 HTTP/1.1
Content-Type: application/json

{
    "name": "Hola",
    "image": "https://acortar.link/2vXTcJ",
    "types": ["Bug"],
    "hp": "1",
    "attack": "1",
    "defense": "2",
    "speed": "2",
    "height": "2",
    "weight": "2"
}


### // Eliminar un Pokemon
DELETE  http://localhost:3001/pokemon/2c32ced6-a9f6-4670-889d-be7998fa1ef9 HTTP/1.1